# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 71c81ee8ae1bd5d67ac28681589093bd7eab4f11b31338d36122387dc8335a74331615f20e8ec19f91441113d3a137b1e6a17b37140ff264b3d78f22e1167ec3

test:
  secret_key_base: 43083d31de309aecb50b998ee12f05bf2578e8283ab7033d030cd507e5a7ed4460bee0a92008be3d3199f13b368e302d076c6c8558592f62020d7de45e2fdf6a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
